### ISSUE TITLE
Why is dot: false by default?

### ISSUE THREAD

**Issue by paulmillr** [micromatch/picomatch#25]
What was the reason for that? For example, chokidar always assumed user would see dotfiles. That's why we've mentioned `ignore: /^./` since initial releases.

I'm thinking of hardcoding it in anymatch or chokidar.

cc @jonschlinkert @bpasero

**Comment by paulmillr** [comment]
@jonschlinkert You're saying it has been the default behavior since micromatch v1 was out?

**Comment by bpasero** [comment]
Would be great if this could change or made configurable. We run a fork of `chokidar` only for that reason.

**Comment by jonschlinkert** [comment]
> Would be great if this could change or made configurable.

The more I think about it this really isn't a picomatch issue as it's already configurable in picomatch. Chokidar could allow options to be passed to picomatch so that you can just do `{ dot: true }`.  If we changed it here, I think it would break a lot of existing implementations and is not what is expected by most users.
