### ISSUE TITLE
Possible to reduce bundled size vs minimatch?

### ISSUE THREAD

**Issue by humphd** [micromatch/picomatch#6]
I was really excited to find picomatch, and wanted to try swapping it for minimatch in our browser library.  I tried building both with Parceljs, and picomatch is 5K larger in a minified bundle.

First minimatch:

```
dist/minimatch.js                                                                               14.56 KB    611ms
├── minimatch.js                                                                                 7.31 KB     17ms
├── ../../../usr/local/lib/node_modules/parcel-bundler/node_modules/process/browser.js           2.27 KB    231ms
├── ../../../usr/local/lib/node_modules/parcel-bundler/node_modules/path-browserify/index.js     2.09 KB      2ms
├── node_modules/brace-expansion/index.js                                                        2.06 KB    176ms
├── node_modules/balanced-match/index.js                                                           601 B    116ms
└── node_modules/concat-map/index.js                                                               259 B     65ms
```

And picomatch:

```
dist/index.js                                19.84 KB    17.55s
├── lib/parse.js                              9.62 KB     681ms
├── lib/picomatch.js                          3.18 KB     758ms
├── node_modules/process/browser.js           2.63 KB     200ms
├── lib/scan.js                               2.13 KB     453ms
├── node_modules/path-browserify/index.js      2.1 KB     166ms
└── index.js                                    116 B    16.08s
```

In the end, picomatch is larger, which surprised me.  Obviously you didn't state that your goal was to make it smaller than minimatch, and I assumed by reading the README.  But I thought I'd file it in case you had any interest in this comparison.  Feel free to close this too if it's not in scope for your work.

**Comment by wtgtybhertgeghgtwtg** [comment]
I'm admittedly not very familiar with `parcel`, so this is just going off `npx parcel build node_modules/picomatch/index.js`, but it looks like it runs stuff through `babel`, so `picomatch`, which [targets `node>=8`](https://github.com/micromatch/picomatch/blob/efe4ec9448069352030473b9a3b4e36345b1478d/package.json#L18), would be transpiled to something more verbose.

**Comment by styfle** [comment]
Here are some numbers for the latest versions:

## Bundle Size
picomatch: ![picomatch](https://badgen.net/bundlephobia/minzip/picomatch)
minimatch: ![minimatch](https://badgen.net/bundlephobia/minzip/minimatch)

## Install Size
picomatch: ![picomatch](https://badgen.net/packagephobia/install/picomatch)
minimatch: ![minimatch](https://badgen.net/packagephobia/install/minimatch)

**Comment by humphd** [comment]
Correct, I used `npx parcel build index.js --detailed-report` to generate those.

Agree, it must be transpiling that's adding the extra weight.

**Comment by jonschlinkert** [comment]
I'm not sure how we'd reduce bundle size since this library has no dependencies, and a very small API surface.

FWIW, the goals with picomatch were: 1) accuracy, and 2) speed.  

I think we achieved both goals, and I used the most optimal parsing strategy I could think of to achieve the first goal. 

If we remove code, we sacrifice accuracy. There will be small optimizations over time, but there also might be necessary code additions as we address edge cases. Minimatch fails something like 20-30% of the unit tests in picomatch, and in terms of speed, if we measure the time-to-first-match (which includes requiring/loading time, parsing, compiling a regular expression, and returning the very first match), picomatch is just as fast or faster in most scenarios. 

IMHO, I guess your decision will come down to which thing matters more: accuracy or smaller bundle size. 

Although... there is one thing I can think of that would reduce bundle size, probably smaller than minimatch. We could remove the `scan` method, which is arguably not necessary in this library. IMHO it's such a tiny amount of code that's it's nice to have on the picomatch API (`scan` is used to split the file path from the glob part of a pattern, which can be used to speed up fs globbing, and you will always be using a matcher together with an operation like this). Thoughts?

**Comment by humphd** [comment]
@jonschlinkert I think optimizing for speed, accuracy, and reducing dependencies are amazing goals, and this does all of that. RE: removing `scan`, I can't speak to the functionality, but the size being added by that isn't really very much:

```
lib/scan.js                               2.13 KB     453ms
```

I just wanted to file something in case there were obvious things that could be done.  It doesn't sound like there are, so let's close this.  Thanks for considering it, and for your work on picomatch.

**Comment by jonschlinkert** [comment]
> I just wanted to file something in case there were obvious things that could be done. 

Absolutely. I'm really appreciative that you wanted to have the conversation, it's always helpful for me to think things through from the perspective of different use cases. 

> Thanks for considering it, and for your work on picomatch.

Made my day! Thanks!
